In [1]:
import cv2
import numpy as np

In [119]:
#loading an image to python
# Replace with the full path of your image
im= cv2.imread('Image_1.jpg')

In [73]:
im2= cv2.imread('imagetowork2.jpg')

In [3]:
#loading an image from a url
import urllib
url = 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Lenna_%28test_image%29.png/220px-Lenna_%28test_image%29.png'
resp = urllib.request.urlopen(url)

In [4]:
resp

In [5]:
im = np.asarray(bytearray(resp.read()), dtype="uint8")
im = cv2.imdecode(im, cv2.IMREAD_COLOR)

In [84]:
im

array([[[233, 145, 109],
        [234, 146, 110],
        [235, 147, 111],
        ...,
        [233, 165, 136],
        [233, 164, 137],
        [234, 165, 138]],

       [[234, 146, 110],
        [235, 147, 111],
        [236, 148, 112],
        ...,
        [234, 166, 137],
        [235, 166, 139],
        [236, 167, 140]],

       [[236, 146, 112],
        [237, 147, 113],
        [239, 149, 115],
        ...,
        [236, 167, 140],
        [235, 168, 141],
        [236, 169, 142]],

       ...,

       [[240, 191, 177],
        [240, 191, 177],
        [240, 191, 177],
        ...,
        [197, 146, 130],
        [238, 186, 170],
        [236, 181, 166]],

       [[240, 191, 177],
        [240, 191, 177],
        [240, 191, 177],
        ...,
        [193, 141, 129],
        [236, 182, 171],
        [239, 183, 172]],

       [[237, 188, 174],
        [237, 188, 174],
        [237, 188, 174],
        ...,
        [232, 179, 169],
        [245, 190, 181],
        [236, 179, 170]]

In [21]:
#display the image
cv2.imshow('from_url',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [95]:
#display the image
cv2.imshow('from_system',im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
type(im)

numpy.ndarray

In [9]:
#get the b,g,r values of 0th pixel
im[0][0]

array([127, 137, 225], dtype=uint8)

In [10]:
im.shape

(220, 220, 3)

In [110]:
blue=im.copy()

In [111]:
blue[:,:,1:3]=0

In [113]:
#cv2.namedWindow("red_image",cv2.WINDOW_NORMAL)
#cv2.resizeWindow("red_image",1920,1200)
cv2.imshow('red_image',blue)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#an image has 3 channels Blue, Green, Red
im.shape

(847, 837, 3)

In [114]:
red = im[:,:,0:2]=0
red.shape

AttributeError: 'int' object has no attribute 'shape'

In [10]:
#To access blue colour
im[:,:,0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [38]:
#splitting blue, green and red channels
b,g,r=cv2.split(im)
b.size

48400

In [16]:
#create a 4X4 color image
rgb = np.random.randint(0,255, size=(4,4,3),dtype=np.uint8)
#display the image
cv2.imshow('random_image',rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
rgb

array([[[172,  58, 241],
        [205, 230,  47],
        [  8,  46,  13],
        [133,  51, 219]],

       [[239, 186, 190],
        [ 76,  98,   3],
        [ 32,  67,  27],
        [234, 188, 125]],

       [[ 71,  57, 119],
        [ 18,  63,  30],
        [ 35, 239, 110],
        [ 80, 184,  55]],

       [[ 31, 171,  78],
        [ 78, 180, 228],
        [166,  18, 200],
        [ 84,  52, 233]]], dtype=uint8)

### Grayscale

Grayscale only contains luminance (brightness) information and no color information; that is why maximum luminance is white and zero luminance is black; everything in between is a shade of gray.

In [17]:
#create a 4X4 grayscale image
gr = np.random.randint(255, size=(4,4),dtype=np.uint8)
#display the image
cv2.imshow('random_grayscale_image',gr)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
#converting image from color to grayscale
gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

In [19]:
#display the gray image
cv2.imshow('image',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
gray.shape

(847, 837)

In [21]:
import sys
print(sys.getsizeof(gray),sys.getsizeof(im))

709051 2126945


### 3 types of grayscale conversion
1. Luminosity
2. Lightness
3. Average

### https://www.johndcook.com/blog/2009/08/24/algorithms-convert-color-grayscale/



### Extract object of a specific color using HSV

In [121]:
#HSV color format for detecting objects with specific color irrespective of lighting condition

#track blue object

#image=cv2.imread('colour-wheel.jpg')
hsv = cv2.cvtColor(im, cv2.COLOR_BGR2HSV)

In [186]:
cv2.imshow('hsv',hsv)
#press any key to quit
cv2.waitKey(0)
cv2.destroyAllWindows()

In [124]:
res = cv2.bitwise_and(im,im)
#cv2.imshow('Original_Image',im)
#cv2.imshow('mask',mask)
cv2.imshow('res',res)
#press any key to quit
cv2.waitKey(0)
cv2.destroyAllWindows()

In [191]:
# define range of blue color in HSV
lower_blue = np.array([255,225,0])
upper_blue = np.array([255,255,255])

# Threshold the HSV image to get only blue colors
mask = cv2.inRange(hsv, lower_blue, upper_blue)

# Bitwise-AND mask and original image
res = cv2.bitwise_and(im,im,mask=mask)
#cv2.imshow('Original_Image',im)
#cv2.imshow('mask',mask)
cv2.imshow('res',res)
#press any key to quit
cv2.waitKey(0)
cv2.destroyAllWindows()

In [128]:
hsv_blue = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
hsv_blue

array([[[120, 255, 255]]], dtype=uint8)

In [189]:
green = np.uint8([[[332,86,100]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
hsv_green

array([[[ 13,  61, 100]]], dtype=uint8)

In [156]:
red=np.uint8([[[0,0,255]]])
hsv_red = cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
hsv_red

array([[[  0, 255, 255]]], dtype=uint8)

In [18]:
#get the range of colors in hsv
blue=np.uint8([[[255,0,0]]])
hsv_blue = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)

green = np.uint8([[[0,255,0 ]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)

red=np.uint8([[[0,0,255]]])
hsv_red = cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
print (hsv_blue)
np.squeeze(hsv_blue)[0]

[[[120 255 255]]]


120

In [177]:
#once you have the exact value of the specific colors, add a threshold of +/-10 to get the lower and upper range
lower_green=np.array([np.squeeze(hsv_green)[0]-10,50,50])
upper_green=np.array([np.squeeze(hsv_green)[0]+10,255,255])

lower_blue = np.array([np.squeeze(hsv_blue)[0]-10,50,50])
upper_blue = np.array([np.squeeze(hsv_blue)[0]+10,255,255])

lower_red = np.array([np.squeeze(hsv_red)[0]-10,50,50])
upper_red = np.array([np.squeeze(hsv_red)[0]+10,255,255])

print(lower_blue,upper_blue)

[110  50  50] [130 255 255]


### Reading multiple images using OS library

In [182]:
import os

In [183]:
#know your current directory
os.getcwd()

'C:\\Users\\amit.amola\\Python Stuff\\Computer Vision'

In [184]:
#list the contents of a directory
#current directory
lis=os.listdir()
lis

['.ipynb_checkpoints',
 'Computer Vision S1.ipynb',
 'CV basics.ipynb',
 'imagetowork.jpg',
 'imagetowork2.jpg',
 'Image_1.jpg',
 'Week 1 Assignment']

In [29]:
#Of a specific folder
path='/home/sreekiran/Projects/Computer_vision/test books/'
lis2=os.listdir(path)
lis2

['image4.jpg',
 'example.jpg',
 'image2.jpg',
 'image1.jpg',
 '.ipynb_checkpoints',
 'image5.jpg',
 'image6.jpg',
 'image3.jpg',
 'book detection.ipynb']

In [30]:
#get only images
#images can also be of .jpeg, .png, .tiff etc. formats. .jpg is most commonly used format
lis_img=list(filter(lambda x:x.endswith('.jpg'),lis))
lis_img

['Global Thresholding.jpg',
 'Adaptive Thresholding Mean.jpg',
 'test.jpg',
 'colour-wheel.jpg',
 'image2.jpg',
 'Adaptive Thresholding Gaussian.jpg',
 'stars1.jpg',
 'stars2.jpg',
 'particles.jpg']

In [31]:
#reading all the images from a folder
images=[]
for f in lis_img:
    #read image
    img=cv2.imread(f)
    images.append(img)

len(images)

9

In [32]:
#to see all the images one by one
for im in images:
    cv2.imshow('image',im)
    #press any key to close the current image and go to next image
    cv2.waitKey(0)
    cv2.destroyAllWindows()